### ISSUE TITLE
Add This Variables Please

### ISSUE THREAD

**Issue by ArturRod** [OHIF/react-vtkjs-viewport#154]
Please could you add this to the original version to be able to clear the cache and re-generate the 3D.
It would be simply adding this:
![image](https://user-images.githubusercontent.com/86238895/136779336-47215c69-c581-4703-859b-221dc253efac.png)
Thanks in advance.

**Comment by shanebenlolo** [comment]
you must fork the repo to your personal account, clone the forked repo, make the required changes, push the changes to your forked repo, and then make a PR from forked repo.
