### ISSUE TITLE
scroll  the mouse but Crosshairs not fllow change

### ISSUE THREAD

**Issue by burgesswu** [OHIF/react-vtkjs-viewport#49]
scroll  the mouse but Crosshairs not fllow change

**Comment by mix3d** [comment]
@dannyrb sounds like an axis representation view

**Comment by dannyrb** [comment]
Our crosshairs tool only updates position when actively used. Long-term, we'll likely want something similar to your implementation, and also subscribe to changes to update our placement.

**Comment by dannyrb** [comment]
Fixed 👍
