### ISSUE TITLE
Crosshairs Failed to Open

### ISSUE THREAD

**Issue by fying-snow** [OHIF/react-vtkjs-viewport#92]
Sorry to bother you, but I can't open the crosshairs demo. It failed because of the requests time out.  I'm not sure whether it  was caused by my network status; but I failed so many times. Do you mind helping me to ensure this problem?
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/10750319/75960985-0cef4b80-5efc-11ea-9913-dbf3bbbf88f7.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/10750319/75960989-0eb90f00-5efc-11ea-85fa-d9e364c7075c.png">

**Comment by dannyrb** [comment]
Steps to reproduce? Do you have an issue using the live site?

**Comment by fying-snow** [comment]
> Steps to reproduce? Do you have an issue using the live site?

Unfortunately, I can't open the live site as well. However, my friend can open it. So sorry to bother you and I'll close this issue.

**Comment by dannyrb** [comment]
No worries. If things change, or if you have additional questions, please don't hesitate to create a new issue :wave:
