### ISSUE TITLE
The image reconstructed by MPR is very small by default. Can any parameter control the size

### ISSUE THREAD

**Issue by wmxj** [OHIF/react-vtkjs-viewport#94]

**Comment by wmxj** [comment]
![1](https://user-images.githubusercontent.com/1752767/78163944-9e11fd80-747b-11ea-945d-ebd6d76d70e9.jpg)

**Comment by dannyrb** [comment]
Can you provide a reproduction?

**Comment by wmxj** [comment]
this.renderer.getActiveCamera().zoom(1.2);
